// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CircleLoading: typeof import('./src/components/CircleLoading.vue')['default']
    CollectionSites: typeof import('./src/components/CollectionSites.vue')['default']
    GoTop: typeof import('./src/components/GoTop.vue')['default']
    IconMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IconMaterialSymbolsArrowCircleUp: typeof import('~icons/material-symbols/arrow-circle-up')['default']
    IconMaterialSymbolsArticle: typeof import('~icons/material-symbols/article')['default']
    IconMaterialSymbolsEditDocumentRounded: typeof import('~icons/material-symbols/edit-document-rounded')['default']
    IconMaterialSymbolsFrameReload: typeof import('~icons/material-symbols/frame-reload')['default']
    IconMaterialSymbolsLibraryMusic: typeof import('~icons/material-symbols/library-music')['default']
    IconMaterialSymbolsMovie: typeof import('~icons/material-symbols/movie')['default']
    IconMaterialSymbolsRefresh: typeof import('~icons/material-symbols/refresh')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    IconMdiReload: typeof import('~icons/mdi/reload')['default']
    IconMidReload: typeof import('~icons/mi/d-reload')['default']
    LinkItem: typeof import('./src/components/LinkItem.vue')['default']
    MediaItem: typeof import('./src/components/MediaItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateButton: typeof import('./src/components/UpdateButton.vue')['default']
  }
}
