// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GoTop: typeof import('./src/components/GoTop.vue')['default']
    IconMaterialSymbolsArrowCircleUp: typeof import('~icons/material-symbols/arrow-circle-up')['default']
    IconMaterialSymbolsArticle: typeof import('~icons/material-symbols/article')['default']
    IconMaterialSymbolsEditDocumentRounded: typeof import('~icons/material-symbols/edit-document-rounded')['default']
    IconMaterialSymbolsLibraryMusic: typeof import('~icons/material-symbols/library-music')['default']
    IconMaterialSymbolsMovie: typeof import('~icons/material-symbols/movie')['default']
    IconMdiGithub: typeof import('~icons/mdi/github')['default']
    LinkItem: typeof import('./src/components/LinkItem.vue')['default']
    MediaItem: typeof import('./src/components/MediaItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
