<template>
  <button
    type="button"
    class="update-button"
    title="网站有更新"
    aria-label="刷新网站以获取最新内容"
  >
    <IconifyIcon
      icon="material-symbols:refresh"
      class="update-button__icon"
      aria-hidden="true"
    />
  </button>
</template>
