import './happy-dom'
import { createSSRApp } from 'vue'
import { renderToString } from 'vue/server-renderer'
import App from './App.vue'
import createRouter from './router'
import workerpool from 'workerpool'

const DocType = '<!DOCTYPE html>'

export const render = async function (url: string) {
  const app = createSSRApp(App)
  const router = createRouter()
  app.use(router)
  // set the router to the desired URL before rendering
  await router.push(url)
  await router.isReady()
  // passing SSR context object which will be available via useSSRContext()
  // @vitejs/plugin-vue injects code into a component's setup() that registers
  // itself on ctx.modules. After the render, ctx.modules would contain all the
  // components that have been instantiated during this render call.
  const html = await renderToString(app)

  // the SSR manifest generated by Vite contains module -> chunk/asset mapping
  // which we can then use to determine what files need to be preloaded for this
  // request.
  console.log('raw rendered html ', url, html)
  document.getElementById('app')!.innerHTML = html
}

workerpool.worker({
  render,
  setHtml(html: string) {
    document.write('')
    document.write(html.replace(DocType, ''))
    console.log('write', html)
    console.log('current html', document.documentElement.outerHTML)
  },
  getHtml() {
    console.log('rendered html', document.documentElement.outerHTML)
    return DocType + '\n' + document.documentElement.outerHTML
  },
})
