name: Build tingyuan blog to github page
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@main
      - name: Build-Deploy
        run: |
          npm run build
          npm run deploy
